version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuserr
      POSTGRES_PASSWORD: ahmad10313
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgresql_data:
  redis_data: 