name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      # نصب وابستگی‌ها (در صورت نیاز)
      - run: |
          if [ -f package.json ]; then
            npm install
            npm run build --if-present
          fi
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
      - id: deployment
        uses: actions/deploy-pages@v2